interface SkillsI {
  name: string;
  isIconShown?: boolean;
  icon?: string;
}

export const skills: string[] = [
  "HTML",
  "CSS",
  "JavaScript",
  "TypeScript",
  "Angular",
  "RxJS",
  "NgRX",
  "Angular Universal",
  "React",
  "React Native",
  "NextJS",
  "Redux",
  "React Query",
  "React Testing Library",
  "Jest",
  "GraphQL",
  "Storybook",
  "Systems Design",
  "styled-component",
  "CSS Modules",
  "Sass",
  "Webpack",
  "NodeJS",
  "Express",
  "MongoDB",
  "OOP",
  "GIT",
  "Web Performance",
  "SEO",
  "Semantic HTML",
  "W3C Accessibility",
  "Data Structures",
  "Docker",
  "CI/CD",
  "Jenkins",
  "AWS",
  "Amazon S3",
  "Amazon EC2",
  "Web Application Security",
  "Sentry",
  "Micro-Frontend",
  "Software Design Patterns",
  "Cypress",
  "Chrome Developer Tools",
  "Linux",
  "Agile",
  "Scrum",
];
